image: node:latest

stages:
  - test

API tests:
  stage: test
  script:
    - npm install
    - npm coingecko
  after_script:
    # -
  artifacts:
    when: always
    paths:
      - mochawesome-report/*
