image: node:latest

stages:
  - test

API tests:
  stage: test
  script:
    - npm install
    - npm run coingecko:mochawesome
    - npm run coingecko:junit
  after_script:
    # -
  artifacts:
    when: always
    paths:
      - mochawesome-report/*
    reports:
      junit: test-results.xml
    expire_in: 1 week
